db:
    driver_name: "postgres"
    database_url: "host=localhost dbname=book_exchange_db_dev sslmode=disable"
    username: "username"
    password: "password"
    port: "5432"
server:
    bind_addr: "8080"
logger:
    level: "debug"